### ISSUE TITLE
Circular dependencies resulting from project structure

### ISSUE THREAD

**Issue by sfwatanabe** [Lockstep-Network/lockstep-sdk-python#4]
The `LockstepApi `class located in `lockstep_api.py`  triggers circular dependency issues as a result of imported classes making use of the `LockstepApi` type annotation. 

Consider the following:

```py
# lockstep_api.py

class LockstepApi():

    """
    Construct a new LockstepApi client object
    """
    def __init__(self, env: str):
        from src.clients.activities_client import ActivitiesClient
...

# .clients.activities_client

from src.lockstep_api import LockstepApi     # This import causes the circular dependency as we begin to bounce between files
from src.models.lockstep_response import LockstepResponse
from src.models.activitymodel import ActivityModel

class ActivitiesClient:

    def __init__(self, client: LockstepApi):
        self.client = client
```
---

## Possible Solutions

- Define a base class with the same interface as the LockstepApi class that can be imported without dependency loop
    - Have LockstepApi inherit the base class, allowing it to given as an argument to clients
    - Would require user instatiates LockstepApi object prior to passing it to client objects
- Convert client classes to instead simply prepare a request that can be passed to the LockstepApi object
    - Still requires user to instantiate both a client and LockstepApi object
- Other ideas...

**Comment by tspence** [comment]
I think we were able to solve this by using this new pattern:

```python
from src.models.lockstep_response import LockstepResponse

class CustomFieldDefinitionsClient:
    from src.lockstep_api import LockstepApi
    from src.models.customfielddefinitionmodel import CustomFieldDefinitionModel

    def __init__(self, client: LockstepApi):
        self.client = client
```

Does this work?

**Comment by sfwatanabe** [comment]
Tried testing locally as an installed package and this will still lead to the circular dependency issue when we get to the LockstepApi import statement. Will be doing some additional work on my local to provide possible solutions. 

I do believe the simplest solution may be to have the client class definitions to live within the lockstep_api.py file. However I'm not sure that's the best solution.

**Comment by tspence** [comment]
We could also simply eliminate the type condition on the "client" object.  We know we control it and it will always be the correct type - maybe that's enough?

**Comment by tspence** [comment]
Is this now resolved?

**Comment by sfwatanabe** [comment]
Everything appears to importing correctly and able to make api calls.
