### ISSUE TITLE
Add additional directory to src for straightforward import name

### ISSUE THREAD

**Issue by sfwatanabe** [Lockstep-Network/lockstep-sdk-python#6]
* Currently the root directory for the package is `src`
* Add a directory below `src` that will serve as the import name when using in Python programs

Mildly working example below successfully imports the package that has been installed via 
`python -m pip install -e path/to/package_root/`

*Note: the `_lockstep_api.py` file is hidden from top level imports but the `LockstepApi` class has been exposed in the `__init__.py` file*

![image](https://user-images.githubusercontent.com/69649930/149561264-6643e833-a5ee-4071-9353-43e758bf5bbc.png)

**Comment by tspence** [comment]
Is this now resolved?
